# MOwNiT 
## Laboratorium
## Wybrane zagadnienia algebry liniowej, faktoryzacja
### Algebra liniowa w Julii
https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/index.html

In [1]:
using(LinearAlgebra)

In [2]:
methods(factorize)

# 11 methods for generic function "factorize":
[1] factorize(A::StridedArray{T, 2}) where T in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\dense.jl:1207
[2] factorize(A::Adjoint) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\dense.jl:1283
[3] factorize(A::Transpose) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\dense.jl:1284
[4] factorize(A::LinearAlgebra.AbstractTriangular) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\triangular.jl:2676
[5] factorize(A::Union{Hermitian{Complex{Float64},var"#s828"}, Hermitian{Float64,var"#s828"}, Symmetric{Float64,var"#s828"}} where var"#s828"<:SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\SparseArrays\src\linalg.jl:1538
[6] factorize(A::Union{Hermitian{T,S}, Symmetric{T,S}} where S where T) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\symmetric.jl:634
[7] factorize(A::Tridiagonal) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\lu.jl:555
[8] factorize(D::Diagonal) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\diagonal.jl:121
[9] factorize(A::Bidiagonal) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\bidiag.jl:875
[10] factorize(S::SymTridiagonal) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\ldlt.jl:166
[11] factorize(A::SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\SparseArrays\src\linalg.jl:1508

In [3]:
#wiersze vs kolumny
x1=[1 2 2]

1×3 Array{Int64,2}:
 1  2  2

In [4]:
y1=[1 ;2 ;3]

3-element Array{Int64,1}:
 1
 2
 3

In [5]:
transpose(x1)

3×1 Transpose{Int64,Array{Int64,2}}:
 1
 2
 2

In [6]:
#iloczyn skalarny
dot(x1,y1)

11

 Długość wektora liczymy jako pierwiastek z jego iloczynu skalarnego 
$$ \lVert\mathbf{v}\rVert = \sqrt{\mathbf{v}\cdot \mathbf{v}}=\sqrt{\sum_{i=1}^nv_i^2}$$



#### Przykładowe dane

In [7]:
#losujemy macierz 3x3
A=rand(3,3)

3×3 Array{Float64,2}:
 0.56313    0.289171  0.00958377
 0.89634    0.827239  0.467947
 0.0997293  0.327809  0.747274

In [8]:
#losujemy wektor x
x=rand(3)

3-element Array{Float64,1}:
 0.05294274313248648
 0.003374635933725223
 0.28953897936501005

In [9]:
# wyliczamy b
b=A*x

3-element Array{Float64,1}:
 0.033564355017457664
 0.18573514859846932
 0.22275120237151172

### Sposoby rozwiązania Ax=b

In [10]:
#mozemy policzyc odwrotność macierzy i wymnożyć
# uwaga: nieefektywne!
inv(A) * b

3-element Array{Float64,1}:
 0.052942743132486536
 0.003374635933725001
 0.2895389793650102

In [11]:
#najlepiej używać zoptymalizowanego operatora "\""
x=A\b

3-element Array{Float64,1}:
 0.05294274313248666
 0.0033746359337249753
 0.28953897936501016

 operator "\\" wybiera odpowiednią faktoryzację:
- https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/#LinearAlgebra.factorize
- https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/#man-linalg-factorizations-1
 


### Faktoryzacja LU

In [12]:
# W przypadku ogólnej macierzy kwadratowej jest to faktoryzacja LU z pivotem
Af=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0        0.0       0.0
 0.111263   1.0       0.0
 0.628255  -0.977845  1.0
U factor:
3×3 Array{Float64,2}:
 0.89634  0.827239  0.467947
 0.0      0.235769  0.695209
 0.0      0.0       0.395401

In [13]:
# Macierz L
Af.L

3×3 Array{Float64,2}:
 1.0        0.0       0.0
 0.111263   1.0       0.0
 0.628255  -0.977845  1.0

In [14]:
#Macierz U
Af.U

3×3 Array{Float64,2}:
 0.89634  0.827239  0.467947
 0.0      0.235769  0.695209
 0.0      0.0       0.395401

In [15]:
# wektor permulatacji wierszy 
Af.p

3-element Array{Int64,1}:
 2
 3
 1

In [16]:
# mozemy zamienic macierz A na postać zfaktoryzowaną
A=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0        0.0       0.0
 0.111263   1.0       0.0
 0.628255  -0.977845  1.0
U factor:
3×3 Array{Float64,2}:
 0.89634  0.827239  0.467947
 0.0      0.235769  0.695209
 0.0      0.0       0.395401

In [17]:
# i działać na niej operatorem \
# operator ten będzie wykorzytywał raz utworzony wynik faktoryzacji
A\b

3-element Array{Float64,1}:
 0.05294274313248666
 0.0033746359337249753
 0.28953897936501016

In [18]:
# dla różnych prawych stron równania z tą samą macierzą
c=rand(3);
A\c

3-element Array{Float64,1}:
  4.706779682150943
 -5.890112438765061
  2.689126538984758

### Faktoryzacja QR


In [19]:
B=rand(10,5)

10×5 Array{Float64,2}:
 0.200128   0.62959    0.130804   0.742079   0.0628618
 0.540098   0.44457    0.514199   0.0572266  0.697732
 0.188178   0.0146121  0.689782   0.852789   0.291199
 0.0286524  0.314136   0.0174425  0.39583    0.721104
 0.386352   0.293115   0.923797   0.719396   0.899595
 0.433053   0.859061   0.699274   0.329396   0.375237
 0.807919   0.238007   0.080032   0.769218   0.0133582
 0.52908    0.0461669  0.277809   0.199828   0.353248
 0.13044    0.0141308  0.791694   0.756507   0.520856
 0.841832   0.625824   0.457654   0.958402   0.72758

In [20]:
# W przypadku ogólnej macierzy prostokątnej wybierana jest faktoryzacja QR z pivotem
factorize(B)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
10×10 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.362686    0.330682    0.436167   -0.339917   …  -0.021263    -0.388402
 -0.0279691  -0.559727    0.204214    0.290453       0.0328353   -0.501645
 -0.416795    0.195077   -0.312485   -0.137341      -0.496478    -0.157132
 -0.193459   -0.404355   -0.029442   -0.372185      -0.00376797  -0.180573
 -0.3516     -0.387776   -0.199332   -0.0866424     -0.384324     0.158507
 -0.16099    -0.146583    0.675536   -0.0781512  …   0.0570351    0.167049
 -0.37595     0.386529    0.0388664   0.557537       0.060684    -0.200993
 -0.0976647  -0.195018   -0.12805     0.470989      -0.0146005   -0.207132
 -0.369738   -0.0486902  -0.367449   -0.207039       0.769188    -0.0735323
 -0.468412   -0.118882    0.14329     0.231411       0.0738925    0.631238
R factor:
5×5 Array{Float64,2}:
 -2.04607  -1.2528   -0.941355  -1.17519   -1.35439
  0.0      -1.18396  -0.396497  -0.321628  -0.693974
  0.0    

- $Q$ to macierz  ortogonalna mxm, co oznacza, że  $Q^T*Q=Q*Q^T=I$ czyli $Q^{-1}=Q^T$ (odwracanie takich macierzy jest szybkie i nie generuje dodatkowych błędów !)
- $R$ to macierz postaci $\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} $ , gdzie $Rfactor$ jest macierzą trójkątną górną, a 0 to macierz zer o wymierze nx(m-n)

### Zastosowanie faktoryzacji do metody najmniejszych kwadratów

Jednym z zastosowań faktoryzacji QR jest użycie jej do metody najmniejszych kwadratów.

Przykład:

Obliczmy dopasowanie wielomianu $$f(x)=wsp_2*x^2+wsp_1*x+wsp_0$$ do punktów (1,1) (2,2) (3,4) (4, 4) (5,3) (6,0)

- Budujemy układ równań wg wzoru $$wsp_2x_i^2+wsp_1x_i+wsp_0=y_i$$:
$$wsp_2*1^2+wsp_1*1+wsp_0=1$$
$$wsp_2*2^2+wsp_1*2+wsp_0=2$$
$$wsp_2*3^2+wsp_1*3+wsp_0=4$$
$$wsp_2*4^2+wsp_1*4+wsp_0=4$$
$$wsp_2*5^2+wsp_1*5+wsp_0=3$$
$$wsp_2*6^2+wsp_1*6+wsp_0=0$$

- Układ ten  nie ma dokładnego rozwiązania. Możemy jednak znaleźć najlepsze przybliżenie, czyli takie $wsp_i$, które minimalizują odległość:

$$\sqrt{\sum_{i=1}^{6}{(y_i-f(x_i))^2}}=\lVert y-A*wsp\rVert$$





Jak użyć do tej mimalizacji faktoryzacji QR:

#### 1. Tworzymy macierz A na postawie $(x_i,y_i)$

In [21]:
A=zeros(6,3) 

6×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

 punkty $(x_i,y_i)$


In [22]:
x=[1; 2 ;3 ;4 ;5 ;6]
y=[1; 2; 4; 4; 3; 0]

6-element Array{Int64,1}:
 1
 2
 4
 4
 3
 0

In [23]:
A[:,1]=x.^2

6-element Array{Int64,1}:
  1
  4
  9
 16
 25
 36

In [24]:
A[:,2]=x

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [25]:
A[:,3]=ones(6)

6-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [26]:
A

6×3 Array{Float64,2}:
  1.0  1.0  1.0
  4.0  2.0  1.0
  9.0  3.0  1.0
 16.0  4.0  1.0
 25.0  5.0  1.0
 36.0  6.0  1.0

#### 2. Dokonujemy faktoryzacji QR macierzy A 

In [27]:
 AF=factorize(A)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
6×6 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.0209657  -0.343313    0.838525   0.112335    -0.0400677  -0.405397
 -0.0838628  -0.521522    0.167705  -0.00636667   0.34634     0.756879
 -0.188691   -0.534625   -0.223607  -0.612934    -0.487947   -0.121617
 -0.335451   -0.382624   -0.33541    0.753648    -0.213523   -0.122449
 -0.524142   -0.0655178  -0.167705  -0.204705     0.705864   -0.390779
 -0.754765    0.416693    0.279508  -0.0419783   -0.310667    0.283364
R factor:
3×3 Array{Float64,2}:
 -47.697  -9.24587  -1.90788
   0.0    -2.34816  -1.43091
   0.0     0.0       0.559017
permutation:
3-element Array{Int64,1}:
 1
 2
 3

In [28]:
# można przetestować ortogonalność:
Transpose(AF.Q)*AF.Q

6×6 Array{Float64,2}:
  1.0           0.0           2.77556e-17  …   2.77556e-17  -8.32667e-17
  0.0           1.0          -8.32667e-17     -5.55112e-17  -6.93889e-17
  2.77556e-17  -8.32667e-17   1.0             -8.32667e-17   0.0
 -4.16334e-17   2.77556e-17  -8.84709e-17     -9.02056e-17  -3.98986e-17
  2.77556e-17  -5.55112e-17  -8.32667e-17      1.0          -1.38778e-17
 -8.32667e-17  -6.93889e-17   0.0          …  -1.38778e-17   1.0

Mamy równanie:
$$A*wsp=y$$
Dla $A=QR$:
$$QR*wsp =y$$
Możemy obydwie strony wymnożyć z lewej przez $Q^T$:
$$R*wsp =Q^T y$$
$$\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} wsp= Q^T y$$

Poszukiwanym rozwiązaniem jest rozwiązanie równania będącego górną niezerową częścią:
$$Rfactor * wsp= Q^T y[1:n]$$
$$wsp=Rfactor \setminus Q^T y[1:n]$$

In [29]:
# implementacja powyższego (uwaga: w tym przykladzie nie jest potrzebna permutacja,
# bo wektor permutacji wynosi[1 2 3])
AF.R\((Transpose(AF.Q)*y)[1:3])

3-element Array{Float64,1}:
 -0.5714285714285723
  3.9428571428571493
 -2.8000000000000136

Więcej informacji:
- http://www.math.uconn.edu/~leykekhman/courses/MATH3795/Lectures/Lecture_8_Linear_least_squares_orthogonal_matrices.pdf
- http://www.seas.ucla.edu/~vandenbe/133A/lectures/qr.pdf

W praktyce używamy tego algorytmu poprzez operator "\\", za którym jest on "schowany".

In [30]:
A \ y

3-element Array{Float64,1}:
 -0.5714285714285723
  3.9428571428571493
 -2.8000000000000136

In [31]:
#sprawdzamy czy dostaliśmy dobre wspólczynniki
using Polynomials
fit(x,y, 2)

Polynomial(-2.800000000000001 + 3.942857142857141*x - 0.5714285714285708*x^2)

In [32]:
@which fit

Polynomials

Funkcja <a href="https://github.com/JuliaMath/Polynomials.jl/blob/master/src/common.jl#L142">
fit</a>  z pakietu Polynomials używa własnie tej metody


### Zadania

#### Zadanie 1 (1pkt)
Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x.
Nastepnie rozwiąż równanie Ax=b trzema metodami:
- inv()
- \
- factorize()

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie funkcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy  od drugiego wywołania !

#### Zadanie 2 (1pkt)
Policz współczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda z użyciem faktoryzacji QR zaprezentowana na tym laboratorium).
Porównaj wyniki z tymi otrzymanymi poprzednio.

#### Zadanie 3 (2 pkt)

Znajdź i zaprezentuj działanie innego zastosowania wybranej faktoryzacji. Przykładowe (ale nie jedyne!) tematy:

-    tworzenie pseudoinversji macierzy (http://buzzard.ups.edu/courses/2014spring/420projects/math420-UPS-spring-2014-macausland-pseudo-inverse-present.pdf).

-   uzycie faktoryzacji QR do znajdowania wartości własnych (https://en.wikipedia.org/wiki/QR_algorithm)

-  zastosowanie faktoryzacji SVD - przykład zastosowania w uczeniu maszynowym https://blog.statsbot.co/singular-value-decomposition-tutorial-52c695315254


